web:
  build: .
  command: php -S 0.0.0.0:8000 -t /code/wordpress
  ports:
    - "8000:8000"
  links:
    - db:mysql
  volumes:
    - .:/code
db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
